### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by roberrrt-s** [CMDA/CSS-to-the-Rescue#1]
Ik heb geen idee hoe ik commits naar jouw master doe, maar moet de & in de title niet &amp; zijn?

**Comment by roberrrt-s** [comment]
Oh, genant, ik bedoel & amp ;

**Comment by vasilisvg** [comment]
Volgens mij hoeft dat niet in HTML5. Maar het is veel ingewikkelder dan ik had gedacht:

https://mathiasbynens.be/notes/ambiguous-ampersands

Groeten,
Vasilis

**Comment by roberrrt-s** [comment]
Dus feitelijk hoeft het niet in HTML5, maar is het meer common practice en netter om het wel te doen? Heb even wat (felle) stackoverflow discussies gezocht, waar de consensus primair ligt op het schrijven van nette code, die beweren voornamelijk hetzelfde

**Comment by vasilisvg** [comment]
Tsja. Als het over code ging dan hadden ze misschien gelijk, daar bij stackoverflow. Maar het gaat hier niet over code, dit is content. Iets wat via een CMS ingevoerd kan worden, bijvoorbeeld door een n00b. Het lijkt me niet wenselijk om zo iemand te gaan dwingen om & amp; te schrijven als ze & bedoelen. 
Je zou er voor kunnen kiezen om de content te parsen en elke & te vervangen door iets wat sommige mensen netjes vinden. Maar dat betekent dat je een ander — echt — probleem niet kunt oplossen. Uiteindelijk ziet het er ook nog eens precies hetzelfde uit.

Ik denk niet dat het common practice is. Maar van mij mag je het aanpassen, als je dat netjes vindt (-:
